services:
  tcp-over-nostr-server:
    build: .
    container_name: tcp-over-nostr-server
    restart: unless-stopped
    
    # Environment variables
    env_file:
      - .env
    
    # Environment variables (can override .env file)
    environment:
      - TON_MODE=server
      - TON_TARGET_HOST=httpbin.org:80
      - TON_TARGET_PORT=80
      - TON_RELAY=wss://relay.damus.io,wss://relay.primal.net,wss://nostr.girino.org
      - TON_VERBOSE=true
      # TON_PRIVATE_KEY=nsec1...
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "tcp-proxy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

# Example usage:
# 1. Copy env.server.example to .env and configure
# 2. Run: docker compose -f docker-compose.server.yml up -d
# 3. Check logs: docker compose -f docker-compose.server.yml logs -f
# 4. Stop: docker compose -f docker-compose.server.yml down
